# Setup
title: Nikhil Kaniyeri
url: https://kaniyeri.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Nikhil Kaniyeri
  url: kaniyeri.github.io/about
  email: kaniyeri@pm.me

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive
  - title: About
    url: /
